## Numpy & Pandas

3. uygulamamızda Numpy kütüphanesini import ederek bazı fonksiyonlarını öğreneceğiz.

Diziler ve matrislerle işlemler yapacağız.

Yaptığımız işlemlerin sebebi yoktur, dizileri, matrisleri ve bazı fonksiyonları, outputları görerek öğrenme amacındayız.

Sonrasında Pandas kütüphanesini import edeceğiz. Dizileri, sözlükleri seriye dönüştürmeyi öğreneceğiz. Kendimiz seri üreteceğiz.



In [3]:
import numpy as np
dizi = np.arange(12).reshape(3,4)  #12 elemanlı 3e 4lük matris
dizi

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [2]:
dizi.shape

(3, 4)

In [3]:
dizi.dtype

dtype('int64')

In [4]:
dizi.itemsize  #elemanların byte'ı

8

In [5]:
dizi.ndim      #dizinin boyutu

2

In [6]:
dizi.size

12

In [7]:
print(dizi)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [11]:
a = np.array([1,2,3])
b = np.array([[1,2,3], [4,5,6]], dtype=np.float64)   #dype = 'float64'    gibi de yazılabiilir.

In [12]:
a.dtype

dtype('int64')

In [17]:
a = np.array([.1,2,3])    #burada a dizisini güncelledik. ilk elemanımız artık .1 yani bir float. a dizisi de artık bir float.
print(a.dtype)
print(a[2])

float64
3.0


In [14]:
b.dtype

dtype('float64')

In [7]:
a=np.zeros((2,2))
print(a)
print("-------------")
b=a=np.ones((1,2))
print(b)
print("-------------")
c=np.full((2,2), 7)
print(c)
print("-------------")
d=np.eye(2)
print(d)
print("-------------")
e=np.random.random((2,2))  #0-1 arası rastgele sayilardan olusacak
print(e)


[[0. 0.]
 [0. 0.]]
-------------
[[1. 1.]]
-------------
[[7 7]
 [7 7]]
-------------
[[1. 0.]
 [0. 1.]]
-------------
[[0.82685873 0.40477227]
 [0.65230198 0.40546771]]


In [19]:
np.arange(2,10,2)    #2 ile 10 arasında 2şer 2şer artarak git

array([2, 4, 6, 8])

In [20]:
np.linspace(0,50,9)    #9 = Oluşturulacak sayıların toplam sayısıdır. Burada 0 ve 50 arasında 11 tane sayı olacak şekilde eşit aralıklı değerler üretilir.

array([ 0.  ,  6.25, 12.5 , 18.75, 25.  , 31.25, 37.5 , 43.75, 50.  ])

In [21]:
np.linspace(0,50,11)    #11 = Oluşturulacak sayıların toplam sayısıdır. Burada 0 ve 50 arasında 11 tane sayı olacak şekilde eşit aralıklı değerler üretilir.

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [23]:
matrix = np.random.randint(0, 101, size= (10,10))    #0 ile 101 e kadar olan random sayılardan, 10a 10luk bir matris üret.
matrix

array([[ 40,  74,  55,  95,  77,  57,  86,  74,  91,   8],
       [ 90,  65,   1,  44,  61,  33,  49,  63,  41,  22],
       [ 65,  15,  72,  90,  56,  96,  74,   2,  81,  86],
       [ 97,  43,  13,  71,  31,  68,  58,  21,  32,  64],
       [ 16,  54,  32,  32,  21,  84,  96,   5,  31,  36],
       [ 82,  25,  82,  74,  51,  72,  46,   9,  31,  85],
       [ 32,  98,  36,  56,  25,  83,  76,  89,  65,  35],
       [ 18,  93,  73,  93,   7,  16,  43, 100,  44,  18],
       [ 60,  90,  71,  46,  92,  45,  31,  98,   4,  53],
       [ 42,   6,  59,  20,  21,  48,   1,  34,   6,  82]])

In [25]:
arr1 = np.array([[4,7], [2,6]], dtype=np.float64)
arr2 = np.array([[3,6], [2,8]], dtype=np.float64)
sum = np.add(arr1, arr2)                           #2 arrayi toplamak(1. elemanla 1. elemanı, 2. elemanla 2. eleman)
print(sum)

[[ 7. 13.]
 [ 4. 14.]]


In [26]:
sum_array = np.sum(arr1)             #arrayi toplamak
print(sum_array)

19.0


In [28]:
sqrt= np.sqrt(arr1)                 #arrayin sqrt almak
print(sqrt)

[[2.         2.64575131]
 [1.41421356 2.44948974]]


In [29]:
trans_arr=arr1.T                    #arrayin transposunu almak (satır-sutun yer degismek)
print(trans_arr)

[[4. 2.]
 [7. 6.]]


In [30]:
a = np.arange(10)*2
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [31]:
a[:9:3] = 50  #0. 3. 9. indexe 50 atadı
a

array([50,  2,  4, 50,  8, 10, 50, 14, 16, 18])

In [32]:
a = np.array([[1,2], [3,4], [5,6]])
bool_idx = a>2
bool_idx

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [33]:
a[bool_idx]    #koşulu sağlayan elemanları yazdırma

array([3, 4, 5, 6])

In [34]:
#veya aynı islem daha kisa sekilde de yapilabilir:
print(a[a>2])

[3 4 5 6]


In [35]:
a = np.array([[2,4,6], [7,1,9]])
b = np.array([[8,3,2], [1,6,0]])
np.vstack((a,b))    #2 diziyi 1 matriste vertical(dikey) birleştirme

array([[2, 4, 6],
       [7, 1, 9],
       [8, 3, 2],
       [1, 6, 0]])

In [36]:
np.hstack((a,b))     #2 diziyi 1 matriste horizontal(yatay) birleştirme

array([[2, 4, 6, 8, 3, 2],
       [7, 1, 9, 1, 6, 0]])

In [40]:
a = np.array([[1,2], [3,4]], dtype=np.float64)
b = np.array([[5,6], [7,8]], dtype=np.float64)
print(np.add(a,b))
print("----")
print(np.subtract(a,b))
print("----")
print(np.multiply(a,b))
print("----")
print(np.divide(a,b))
print("----")
print(np.sqrt(a))

[[ 6.  8.]
 [10. 12.]]
----
[[-4. -4.]
 [-4. -4.]]
----
[[ 5. 12.]
 [21. 32.]]
----
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
----
[[1.         1.41421356]
 [1.73205081 2.        ]]


matrislerde dot fonksiyonu kullanarak işlem yaparız

In [45]:
matrix = np.random.randint(1, 51, size= (5,5))
matrix

array([[18, 43, 31,  2, 40],
       [46, 38, 13, 30, 36],
       [45, 47,  7,  7, 41],
       [27, 40, 38, 18, 32],
       [46, 36, 33, 18, 47]])

In [74]:
sutun_sum = np.sum(matrix, axis=0)      #sütun       
sutun_sum  

array([182, 204, 122,  75, 196])

In [53]:
satir_sum = np.sum(matrix, axis=1)      #satır   
satir_sum  

array([134, 163, 147, 155, 180])

In [ ]:
#numpyda 0 sütunu, 1 ise satırı ifade eder.
#Fakat pandasta tam tersidir.

In [59]:
matrix2 = matrix[1:4, 1:4]
matrix2

array([[38, 13, 30],
       [47,  7,  7],
       [40, 38, 18]])

In [66]:
min_element=np.amin(matrix2)    #np.amin fonksiyonu, bir NumPy dizisinin (array) en küçük değerini bulur.

7

In [67]:
max_element=np.amax(matrix2)    #np.amin fonksiyonu, bir NumPy dizisinin (array) en büyük değerini bulur

47

In [76]:
sorted_matrix = np.sort(matrix,axis=None)[::-1]    #dizi elemanlarını büyükten küçüğe sıralar
#sorted_matrix = np.sort(matrix)
sorted_matrix


#axis=None, diziyi çok boyutlu olsa bile tek boyutlu bir dizi gibi ele alır ve tüm elemanları düzleştirip sıralar.
#[::-1] bu slicing tekniği, sıralı dizinin elemanlarını ters çevirir. (büyükten küçüğe olur)

array([47, 47, 46, 46, 45, 43, 41, 40, 40, 38, 38, 36, 36, 33, 32, 31, 30,
       27, 18, 18, 18, 13,  7,  7,  2])

In [77]:
#1
matrix = np.random.randint(0, 100, size= (10,10))
matrix

array([[ 6, 91, 49, 32, 27, 95, 31, 43, 45, 96],
       [12, 23,  0, 31, 26,  7, 86, 23, 45, 34],
       [ 8,  7, 77, 30, 22, 79, 29, 32, 62, 25],
       [69, 18, 49, 83, 54, 54, 33, 59, 62, 67],
       [44, 61, 81, 24, 37, 99,  9, 80, 65, 78],
       [16, 48, 34, 78, 67, 76, 20, 25, 71, 64],
       [90, 88, 30, 26,  3, 30, 30, 39, 92, 35],
       [56, 31, 19, 41,  7, 87, 10, 20, 13, 76],
       [40, 69, 54, 29, 69, 23, 41, 57, 12, 82],
       [39, 11, 78, 29, 32, 21, 90, 64, 57,  3]])

In [85]:
#2
matrix_satir=np.argmax(matrix, axis=1)    #np.argmax fonksiyonu, bir NumPy dizisinde en büyük değerin indeksini döndürür
matrix_satir

array([9, 6, 5, 3, 5, 3, 8, 5, 9, 6])

In [86]:
#2
matrix_sutun=np.argmax(matrix, axis=0)
matrix_sutun

array([6, 0, 4, 3, 8, 4, 9, 4, 6, 0])

In [95]:
#3
matrix[matrix%2==1] = -1    #tek sayıların yerine -1 değeri atama
matrix

array([[ 6, -1, -1, 32, -1, -1, -1, -1, -1, 96],
       [12, -1,  0, -1, 26, -1, 86, -1, -1, 34],
       [ 8, -1, -1, 30, 22, -1, -1, 32, 62, -1],
       [-1, 18, -1, -1, 54, 54, -1, -1, 62, -1],
       [44, -1, -1, 24, -1, -1, -1, 80, -1, 78],
       [16, 48, 34, 78, -1, 76, 20, -1, -1, 64],
       [90, 88, 30, 26, -1, 30, 30, -1, 92, -1],
       [56, -1, -1, -1, -1, -1, 10, 20, -1, 76],
       [40, -1, 54, -1, -1, -1, -1, -1, 12, 82],
       [-1, -1, 78, -1, 32, -1, 90, 64, -1, -1]])

In [105]:
#4
matrix2 = matrix[:3, -3:]    #matrisin ilk 3 satırı ve son üç sütununu seç
matrix2

array([[-1, -1, 96],
       [-1, -1, 34],
       [32, 62, -1]])

In [106]:
#5
sutun_sum = np.sum(matrix2, axis=0)             
sutun_sum  

array([ 30,  60, 129])

In [107]:
#5
satir_sum = np.sum(matrix2, axis=1)             
satir_sum

array([94, 32, 93])

In [108]:
#6
std_dev = np.std(matrix, axis=0)  #sütunlar boyunca standart sapma bulma
std_dev

array([28.25597282, 28.66722868, 27.22664136, 24.17126393, 18.62149296,
       26.94086116, 34.00720512, 28.83747562, 33.72476835, 38.61139728])

In [109]:
#7
matrix_mean= np.mean(matrix)
centered_matrix= matrix - matrix_mean
print("Ortalama:", matrix_mean)
print("Merkezlenmiş Matris:\n", centered_matrix)


array([[-15.43, -22.43, -22.43,  10.57, -22.43, -22.43, -22.43, -22.43,
        -22.43,  74.57],
       [ -9.43, -22.43, -21.43, -22.43,   4.57, -22.43,  64.57, -22.43,
        -22.43,  12.57],
       [-13.43, -22.43, -22.43,   8.57,   0.57, -22.43, -22.43,  10.57,
         40.57, -22.43],
       [-22.43,  -3.43, -22.43, -22.43,  32.57,  32.57, -22.43, -22.43,
         40.57, -22.43],
       [ 22.57, -22.43, -22.43,   2.57, -22.43, -22.43, -22.43,  58.57,
        -22.43,  56.57],
       [ -5.43,  26.57,  12.57,  56.57, -22.43,  54.57,  -1.43, -22.43,
        -22.43,  42.57],
       [ 68.57,  66.57,   8.57,   4.57, -22.43,   8.57,   8.57, -22.43,
         70.57, -22.43],
       [ 34.57, -22.43, -22.43, -22.43, -22.43, -22.43, -11.43,  -1.43,
        -22.43,  54.57],
       [ 18.57, -22.43,  32.57, -22.43, -22.43, -22.43, -22.43, -22.43,
         -9.43,  60.57],
       [-22.43, -22.43,  56.57, -22.43,  10.57, -22.43,  68.57,  42.57,
        -22.43, -22.43]])

In [112]:
import pandas as pd
indisler = ['Ali', 'Ahmet', 'Mehmet', 'Veli', 'Arda', 'Doruk']
degerler=[5,54,12,22,15,87]
a=pd.Series(degerler, index=indisler)
a

Ali        5
Ahmet     54
Mehmet    12
Veli      22
Arda      15
Doruk     87
dtype: int64

In [132]:
import pandas as pd
indisler = ['Ali', 'Ahmet', 'Mehmet', 'Veli', 'Arda', 'Doruk']
degerler=[5,54,12,22,15,87]
a=pd.Series(degerler, index=indisler)
print(a[['Mehmet', 'Arda', 'Ali']])

type(a)

Mehmet    12
Arda      15
Ali        5
dtype: int64


pandas.core.series.Series

In [121]:
print(a*5+2)
print(np.sqrt(a))

Ali        27
Ahmet     272
Mehmet     62
Veli      112
Arda       77
Doruk     437
dtype: int64
Ali       2.236068
Ahmet     7.348469
Mehmet    3.464102
Veli      4.690416
Arda      3.872983
Doruk     9.327379
dtype: float64


In [134]:
print(a[a>50])

Ahmet    54
Doruk    87
dtype: int64


In [135]:
ogrenciler = {
    'isim' : ['Ali', 'Ahmet', 'Mehmet', 'Veli', 'Arda', 'Doruk'],
    'not'  : [5,54,12,22,15,87],
    'yas'  : [21,24,18,28,20,22]}

a=pd.DataFrame(ogrenciler)
a

isim  not  yas
0     Ali    5   21
1   Ahmet   54   24
2  Mehmet   12   18
3    Veli   22   28
4    Arda   15   20
5   Doruk   87   22

In [136]:
print(a['not']*1.5)
print(a['yas'].sum())

0      7.5
1     81.0
2     18.0
3     33.0
4     22.5
5    130.5
Name: not, dtype: float64
133


In [140]:
a=pd.DataFrame(ogrenciler, columns=['isim', 'not', 'yas', 'giris'])
a

isim  not  yas giris
0     Ali    5   21   NaN
1   Ahmet   54   24   NaN
2  Mehmet   12   18   NaN
3    Veli   22   28   NaN
4    Arda   15   20   NaN
5   Doruk   87   22   NaN

In [141]:
a.T

0      1       2     3     4      5
isim   Ali  Ahmet  Mehmet  Veli  Arda  Doruk
not      5     54      12    22    15     87
yas     21     24      18    28    20     22
giris  NaN    NaN     NaN   NaN   NaN    NaN